import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedCTAButtonWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedGoogleButtonWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedPatternWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedFOrmWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedFacebookButtonWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsigninwidget/generated/GeneratedTextWidget1.dart';

/* Frame Sign in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 244, 255, 235),
                ),
              ),
              Positioned(
                left: 1.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPatternWidget(),
              ),
              Positioned(
                left: 117.0,
                top: 695.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 57.0,
                child: GeneratedCTAButtonWidget(),
              ),
              Positioned(
                left: 198.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 57.0,
                child: GeneratedGoogleButtonWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 57.0,
                child: GeneratedFacebookButtonWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 126.0,
                child: GeneratedFOrmWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 349.0,
                child: GeneratedTextWidget1(),
              ),
              Positioned(
                left: 101.0,
                top: 53.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 62.0,
                child: GeneratedLogoWidget(),
              )
            ]),
      ),
    ));
  }
}
