import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedRestaurantNameWidget1.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedRestaurantNameWidget3.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedEmailFormWidget1.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedTestimonialFrameWidget2.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedPhotoRestaurantWidget2.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedDownload41Widget1.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedTestimonialFrameWidget4.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedTestimonialFrameWidget3.dart';
import 'package:flutterapp/kelompok8app/generatedkolomsearchingwidget/generated/GeneratedRestaurantNameWidget2.dart';

/* Frame kolom searching
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKolomsearchingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 374.0,
        height: 811.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 128.0,
                child: GeneratedTestimonialFrameWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 128.0,
                child: GeneratedTestimonialFrameWidget3(),
              ),
              Positioned(
                left: 18.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 128.0,
                child: GeneratedTestimonialFrameWidget4(),
              ),
              Positioned(
                left: 151.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 23.0,
                child: GeneratedRestaurantNameWidget1(),
              ),
              Positioned(
                left: 151.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 23.0,
                child: GeneratedRestaurantNameWidget2(),
              ),
              Positioned(
                left: 151.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 26.0,
                child: GeneratedRestaurantNameWidget3(),
              ),
              Positioned(
                left: 337.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 230.0,
                child: GeneratedDownload41Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 230.0,
                child: GeneratedPhotoRestaurantWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 57.0,
                child: GeneratedEmailFormWidget1(),
              )
            ]),
      ),
    ));
  }
}
