import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedPatternWidget2.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedFormWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedCheckListWidget.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedCTAButtonWidget1.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/kelompok8app/generatedsignupwidget/generated/GeneratedTextWidget3.dart';

/* Frame Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 243, 255, 234),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedPatternWidget2(),
              ),
              Positioned(
                left: 100.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 57.0,
                child: GeneratedCTAButtonWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 195.0,
                child: GeneratedFormWidget(),
              ),
              Positioned(
                left: 94.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 56.0,
                child: GeneratedCheckListWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 476.0,
                child: GeneratedTextWidget3(),
              ),
              Positioned(
                left: 101.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 62.0,
                child: GeneratedLogoWidget1(),
              )
            ]),
      ),
    ));
  }
}
